<!DOCTYPE html>
<html>
    <head>
        <title>ChosenVille</title>
        <meta charset="UTF-8"/>
        <meta name="keywords" content="ukraine, cities,  rating, top,  live"/>
        <meta name="description" content="Міста України для проживання."/>
        <link rel="icon" href="res/favicon.ico" />
        <link rel="stylesheet" href="style/style.css" type="text/css"/>
    </head>
    <body>
        <div id="wrapper"> 
            <div id="header"></div>
            
            <div id ="nav"><ul>
                <li class="linav"><a href="index.php" class="nav">Головна</a></li>
                <li class="linav"><a href="turist.php" class="nav">Варто відвідати</a></li>
                <li class="linav"><a href="topToVisit.xml" class="nav">Вибір міста проживання</a></li>
                <li class="linav"><a href="users.xml" class="nav">Користувачі</a></li>
                <li class="linav"><a href="registration.php" class="nav">Реєстрація</a></li>
            </ul></div>
            
            <br>          
            <div id="content">
                            <script type="text/javascript" src="registration.js"></script>
                <form action="registration.php">
                    <p><label for="login">Ім’я:</label>*
                    <input type="text" name="login" id="login" /></p>
                    <p><label for="pw">Пароль:</label>*
                    <input type="password" name="pw" id="pw" /></p>
                    <p><label for="pw2">Підтвердження паролю:</label>*
                    <input type="password" name="pw2" id="pw2" /></p>
                    <p><label for="mail">Адрес електронної пошти:</label>*
                    <input type="text" name="mail" id="mail" /></p>
                    <p><label for="sex">Стать:</label>
                        <input type="radio" name="sex" value="man" checked style="display:inline;">чоловіча
                        <input type="radio" name="sex" value="woman" style="display:inline;" >жіноча
                    </p>
                    <p><label for="bd">День народження*:</label><br>
                    <select name="day" id="day" onchange="" style="display:inline; width: 5em" size="1">
                        <option value="01">01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                    </select>
                    <select name="month" id="month" onchange="" style="display:inline; width: 9em" size="1">
                        <option value="01">Січень</option>
                        <option value="02">Лютий</option>
                        <option value="03">Березень</option>
                        <option value="04">Квітень</option>
                        <option value="05">Травень</option>
                        <option value="06">Червень</option>
                        <option value="07">Липень</option>
                        <option value="08">Серпень</option>
                        <option value="09">Вересень</option>
                        <option value="10">Жовтень</option>
                        <option value="11">Листопад</option>
                        <option value="12">Грудень</option>
                    </select>
                    <select name="year" id="year" onchange="" style="display:inline; width: 6em" size="1">
                        <option value="2013">2013</option>
                        <option value="2012">2012</option>
                        <option value="2011">2011</option>
                        <option value="2010">2010</option>
                        <option value="2009">2009</option>
                        <option value="2008">2008</option>
                        <option value="2007">2007</option>
                        <option value="2006">2006</option>
                        <option value="2005">2005</option>
                        <option value="2004">2004</option>
                        <option value="2003">2003</option>
                        <option value="2002">2002</option>
                        <option value="2001">2001</option>
                        <option value="2000">2000</option>
                        <option value="1999">1999</option>
                        <option value="1998">1998</option>
                        <option value="1997">1997</option>
                        <option value="1996">1996</option>
                        <option value="1995">1995</option>
                        <option value="1994">1994</option>
                        <option value="1993">1993</option>
                        <option value="1992">1992</option>
                        <option value="1991">1991</option>
                        <option value="1990">1990</option>
                        <option value="1989">1989</option>
                        <option value="1988">1988</option>
                        <option value="1987">1987</option>
                        <option value="1986">1986</option>
                        <option value="1985">1985</option>
                        <option value="1984">1984</option>
                        <option value="1983">1983</option>
                        <option value="1982">1982</option>
                        <option value="1981">1981</option>
                        <option value="1980">1980</option>
                        <option value="1979">1979</option>
                        <option value="1978">1978</option>
                        <option value="1977">1977</option>
                        <option value="1976">1976</option>
                        <option value="1975">1975</option>
                        <option value="1974">1974</option>
                        <option value="1973">1973</option>
                        <option value="1972">1972</option>
                        <option value="1971">1971</option>
                        <option value="1970">1970</option>
                        <option value="1969">1969</option>
                        <option value="1968">1968</option>
                        <option value="1967">1967</option>
                        <option value="1966">1966</option>
                        <option value="1965">1965</option>
                        <option value="1964">1964</option>
                        <option value="1963">1963</option>
                        <option value="1962">1962</option>
                        <option value="1961">1961</option>
                        <option value="1960">1960</option>
                        <option value="1959">1959</option>
                        <option value="1958">1958</option>
                        <option value="1957">1957</option>
                        <option value="1956">1956</option>
                        <option value="1955">1955</option>
                        <option value="1954">1954</option>
                        <option value="1953">1953</option>
                        <option value="1952">1952</option>
                        <option value="1951">1951</option>
                        <option value="1950">1950</option>
                        <option value="1949">1949</option>
                        <option value="1948">1948</option>
                        <option value="1947">1947</option>
                        <option value="1946">1946</option>
                        <option value="1945">1945</option>
                        <option value="1944">1944</option>
                        <option value="1943">1943</option>
                        <option value="1942">1942</option>
                        <option value="1941">1941</option>
                        <option value="1940">1940</option>
                        <option value="1939">1939</option>
                        <option value="1938">1938</option>
                        <option value="1937">1937</option>
                        <option value="1936">1936</option>
                        <option value="1935">1935</option>
                        <option value="1934">1934</option>
                        <option value="1933">1933</option>
                        <option value="1932">1932</option>
                        <option value="1931">1931</option>
                        <option value="1930">1930</option>
                        <option value="1929">1929</option>
                        <option value="1928">1928</option>
                        <option value="1927">1927</option>
                        <option value="1926">1926</option>
                        <option value="1925">1925</option>
                        <option value="1924">1924</option>
                        <option value="1923">1923</option>
                        <option value="1922">1922</option>
                        <option value="1921">1921</option>
                        <option value="1920">1920</option>
                        <option value="1919">1919</option>
                        <option value="1918">1918</option>
                        <option value="1917">1917</option>
                        <option value="1916">1916</option>
                        <option value="1915">1915</option>
                        <option value="1914">1914</option>
                        <option value="1913">1913</option>
                        <option value="1912">1912</option>
                        <option value="1911">1911</option>
                        <option value="1910">1910</option>
                        <option value="1909">1909</option>
                        </select>
                    </p>
                    <p><label for="city">Місто проживання*:</label><br>
                        <select name="city" id ="city" onkeypress="" size ="1">
                            <option value="Авдіївка">Авдіївка</option>
                            <option value="Алмазна">Алмазна</option>
                            <option value="Алупка">Алупка</option>
                            <option value="Алушта">Алушта</option>
                            <option value="Алчевськ">Алчевськ</option>
                            <option value="Амвросіївка">Амвросіївка</option>
                            <option value="Ананьїв">Ананьїв</option>
                            <option value="Андрушівка (місто)">Андрушівка (місто)</option>
                            <option value="Антрацит (місто)">Антрацит (місто)</option>
                            <option value="Апостолове">Апостолове</option>
                            <option value="Армянськ">Армянськ</option>
                            <option value="Артемівськ (Луганська область)">Артемівськ (Луганська область)</option>
                            <option value="Артемівськ (Донецька область)">Артемівськ (Донецька область)</option>
                            <option value="Артемове">Артемове</option>
                            <option value="Арциз">Арциз</option>
                            <option value="Балаклія">Балаклія</option>
                            <option value="Балта">Балта</option>
                            <option value="Бар">Бар</option>
                            <option value="Баранівка">Баранівка</option>
                            <option value="Барвінкове">Барвінкове</option>
                            <option value="Батурин">Батурин</option>
                            <option value="Бахмач">Бахмач</option>
                            <option value="Бахчисарай">Бахчисарай</option>
                            <option value="Баштанка">Баштанка</option>
                            <option value="Белз">Белз</option>
                            <option value="Бердичів">Бердичів</option>
                            <option value="Бердянськ">Бердянськ</option>
                            <option value="Берегове (місто)">Берегове (місто)</option>
                            <option value="Бережани">Бережани</option>
                            <option value="Березань (місто)">Березань (місто)</option>
                            <option value="Березівка (місто)">Березівка (місто)</option>
                            <option value="Березне (місто)">Березне (місто)</option>
                            <option value="Берестечко">Берестечко</option>
                            <option value="Берислав">Берислав</option>
                            <option value="Бершадь">Бершадь</option>
                            <option value="Бібрка">Бібрка</option>
                            <option value="Біла Церква">Біла Церква</option>
                            <option value="Білгород-Дністровський">Білгород-Дністровський</option>
                            <option value="Білицьке">Білицьке</option>
                            <option value="Білогірськ">Білогірськ</option>
                            <option value="Білозерське">Білозерське</option>
                            <option value="Білопілля">Білопілля</option>
                            <option value="Біляївка (місто)">Біляївка (місто)</option>
                            <option value="Бобринець">Бобринець</option>
                            <option value="Бобровиця">Бобровиця</option>
                            <option value="Богодухів">Богодухів</option>
                            <option value="Богуслав">Богуслав</option>
                            <option value="Болград">Болград</option>
                            <option value="Болехів">Болехів</option>
                            <option value="Борзна">Борзна</option>
                            <option value="Борислав">Борислав</option>
                            <option value="Бориспіль">Бориспіль</option>
                            <option value="Борщів">Борщів</option>
                            <option value="Боярка">Боярка</option>
                            <option value="Бровари">Бровари</option>
                            <option value="Броди">Броди</option>
                            <option value="Брянка">Брянка</option>
                            <option value="Буринь">Буринь</option>
                            <option value="Бурштин (місто)">Бурштин (місто)</option>
                            <option value="Буськ">Буськ</option>
                            <option value="Буча">Буча</option>
                            <option value="Бучач">Бучач</option>
                            <option value="Валки (місто)">Валки (місто)</option>
                            <option value="Василівка (місто)">Василівка (місто)</option>
                            <option value="Васильків">Васильків</option>
                            <option value="Ватутіне">Ватутіне</option>
                            <option value="Вахрушеве">Вахрушеве</option>
                            <option value="Вашківці (місто)">Вашківці (місто)</option>
                            <option value="Великі Мости">Великі Мости</option>
                            <option value="Верхівцеве">Верхівцеве</option>
                            <option value="Верхньодніпровськ">Верхньодніпровськ</option>
                            <option value="Вижниця">Вижниця</option>
                            <option value="Вилкове">Вилкове</option>
                            <option value="Винники">Винники</option>
                            <option value="Виноградів">Виноградів</option>
                            <option value="Вишгород">Вишгород</option>
                            <option value="Вишневе (місто)">Вишневе (місто)</option>
                            <option value="Вільногірськ">Вільногірськ</option>
                            <option value="Вільнянськ">Вільнянськ</option>
                            <option value="Вінниця">Вінниця</option>
                            <option value="Вовчанськ">Вовчанськ</option>
                            <option value="Вознесенськ">Вознесенськ</option>
                            <option value="Волноваха">Волноваха</option>
                            <option value="Володимир-Волинський">Володимир-Волинський</option>
                            <option value="Волочиськ">Волочиськ</option>
                            <option value="Ворожба (місто)">Ворожба (місто)</option>
                            <option value="Вуглегірськ">Вуглегірськ</option>
                            <option value="Вугледар">Вугледар</option>
                            <option value="Гадяч">Гадяч</option>
                            <option value="Гайворон">Гайворон</option>
                            <option value="Гайсин">Гайсин</option>
                            <option value="Галич">Галич</option>
                            <option value="Генічеськ">Генічеськ</option>
                            <option value="Герца">Герца</option>
                            <option value="Гірник (місто)">Гірник (місто)</option>
                            <option value="Гірське">Гірське</option>
                            <option value="Глиняни">Глиняни</option>
                            <option value="Глобине">Глобине</option>
                            <option value="Глухів">Глухів</option>
                            <option value="Гнівань">Гнівань</option>
                            <option value="Гола Пристань">Гола Пристань</option>
                            <option value="Горлівка">Горлівка</option>
                            <option value="Городенка">Городенка</option>
                            <option value="Городище (місто)">Городище (місто)</option>
                            <option value="Городня">Городня</option>
                            <option value="Городок (Львівська область)">Городок (Львівська область)</option>
                            <option value="Городок (Хмельницька область)">Городок (Хмельницька область)</option>
                            <option value="Горохів">Горохів</option>
                            <option value="Гребінка">Гребінка</option>
                            <option value="Гуляйполе">Гуляйполе</option>
                            <option value="Дебальцеве">Дебальцеве</option>
                            <option value="Деражня">Деражня</option>
                            <option value="Дергачі">Дергачі</option>
                            <option value="Джанкой">Джанкой</option>
                            <option value="Дзержинськ">Дзержинськ</option>
                            <option value="Димитров">Димитров</option>
                            <option value="Дніпродзержинськ">Дніпродзержинськ</option>
                            <option value="Дніпропетровськ">Дніпропетровськ</option>
                            <option value="Дніпрорудне">Дніпрорудне</option>
                            <option value="Добромиль">Добромиль</option>
                            <option value="Добропілля">Добропілля</option>
                            <option value="Докучаєвськ">Докучаєвськ</option>
                            <option value="Долина (місто)">Долина (місто)</option>
                            <option value="Долинська">Долинська</option>
                            <option value="Донецьк">Донецьк</option>
                            <option value="Дрогобич">Дрогобич</option>
                            <option value="Дружба (місто)">Дружба (місто)</option>
                            <option value="Дружківка">Дружківка</option>
                            <option value="Дубляни">Дубляни</option>
                            <option value="Дубно">Дубно</option>
                            <option value="Дубровиця">Дубровиця</option>
                            <option value="Дунаївці">Дунаївці</option>
                            <option value="Енергодар">Енергодар</option>
                            <option value="Євпаторія">Євпаторія</option>
                            <option value="Єнакієве">Єнакієве</option>
                            <option value="Жашків">Жашків</option>
                            <option value="Жданівка (місто)">Жданівка (місто)</option>
                            <option value="Жидачів">Жидачів</option>
                            <option value="Житомир">Житомир</option>
                            <option value="Жмеринка">Жмеринка</option>
                            <option value="Жовква">Жовква</option>
                            <option value="Жовті Води">Жовті Води</option>
                            <option value="Заліщики">Заліщики</option>
                            <option value="Запоріжжя">Запоріжжя</option>
                            <option value="Заставна">Заставна</option>
                            <option value="Збараж">Збараж</option>
                            <option value="Зборів">Зборів</option>
                            <option value="Звенигородка">Звенигородка</option>
                            <option value="Здолбунів">Здолбунів</option>
                            <option value="Зеленодольськ">Зеленодольськ</option>
                            <option value="Зимогір'я">Зимогір'я</option>
                            <option value="Зіньків">Зіньків</option>
                            <option value="Зміїв">Зміїв</option>
                            <option value="Знам'янка (місто)">Знам'янка (місто)</option>
                            <option value="Золоте">Золоте</option>
                            <option value="Золотоноша">Золотоноша</option>
                            <option value="Золочів (місто)">Золочів (місто)</option>
                            <option value="Зоринськ">Зоринськ</option>
                            <option value="Зугрес">Зугрес</option>
                            <option value="Івано-Франківськ">Івано-Франківськ</option>
                            <option value="Ізмаїл">Ізмаїл</option>
                            <option value="Ізюм">Ізюм</option>
                            <option value="Ізяслав">Ізяслав</option>
                            <option value="Іллінці (місто)">Іллінці (місто)</option>
                            <option value="Іллічівськ">Іллічівськ</option>
                            <option value="Іловайськ">Іловайськ</option>
                            <option value="Інкерман">Інкерман</option>
                            <option value="Ірміно">Ірміно</option>
                            <option value="Ірпінь (місто)">Ірпінь (місто)</option>
                            <option value="Іршава">Іршава</option>
                            <option value="Ічня">Ічня</option>
                            <option value="Кагарлик (місто)">Кагарлик (місто)</option>
                            <option value="Калинівка (місто)">Калинівка (місто)</option>
                            <option value="Калуш">Калуш</option>
                            <option value="Кам'янець-Подільський">Кам'янець-Подільський</option>
                            <option value="Кам'янка-Бузька">Кам'янка-Бузька</option>
                            <option value="Кам'янка-Дніпровська">Кам'янка-Дніпровська</option>
                            <option value="Кам'янка (місто)">Кам'янка (місто)</option>
                            <option value="Камінь-Каширський">Камінь-Каширський</option>
                            <option value="Канів">Канів</option>
                            <option value="Карлівка (місто)">Карлівка (місто)</option>
                            <option value="Каховка">Каховка</option>
                            <option value="Керч">Керч</option>
                            <option value="Київ">Київ</option>
                            <option value="Ківерці">Ківерці</option>
                            <option value="Кілія">Кілія</option>
                            <option value="Кіровоград">Кіровоград</option>
                            <option value="Кіровськ (Луганська область)">Кіровськ (Луганська область)</option>
                            <option value="Кіровське (місто)">Кіровське (місто)</option>
                            <option value="Кіцмань">Кіцмань</option>
                            <option value="Кобеляки">Кобеляки</option>
                            <option value="Ковель">Ковель</option>
                            <option value="Кодима (місто)">Кодима (місто)</option>
                            <option value="Козятин">Козятин</option>
                            <option value="Коломия">Коломия</option>
                            <option value="Комарно">Комарно</option>
                            <option value="Комсомольськ (місто)">Комсомольськ (місто)</option>
                            <option value="Комсомольське (місто)">Комсомольське (місто)</option>
                            <option value="Конотоп">Конотоп</option>
                            <option value="Копичинці">Копичинці</option>
                            <option value="Корець">Корець</option>
                            <option value="Коростень">Коростень</option>
                            <option value="Коростишів">Коростишів</option>
                            <option value="Корсунь-Шевченківський">Корсунь-Шевченківський</option>
                            <option value="Корюківка">Корюківка</option>
                            <option value="Косів">Косів</option>
                            <option value="Костопіль">Костопіль</option>
                            <option value="Костянтинівка">Костянтинівка</option>
                            <option value="Котовськ">Котовськ</option>
                            <option value="Краматорськ">Краматорськ</option>
                            <option value="Красилів">Красилів</option>
                            <option value="Красний Лиман">Красний Лиман</option>
                            <option value="Красний Луч">Красний Луч</option>
                            <option value="Красноармійськ">Красноармійськ</option>
                            <option value="Красногорівка">Красногорівка</option>
                            <option value="Красноград">Красноград</option>
                            <option value="Краснодон">Краснодон</option>
                            <option value="Красноперекопськ">Красноперекопськ</option>
                            <option value="Кременець">Кременець</option>
                            <option value="Кременчук">Кременчук</option>
                            <option value="Кремінна">Кремінна</option>
                            <option value="Кривий Ріг">Кривий Ріг</option>
                            <option value="Кролевець">Кролевець</option>
                            <option value="Кузнецовськ">Кузнецовськ</option>
                            <option value="Куп'янськ">Куп'янськ</option>
                            <option value="Курахове">Курахове</option>
                            <option value="Ладижин">Ладижин</option>
                            <option value="Ланівці">Ланівці</option>
                            <option value="Лебедин">Лебедин</option>
                            <option value="Липовець (місто)">Липовець (місто)</option>
                            <option value="Лисичанськ">Лисичанськ</option>
                            <option value="Лозова (місто)">Лозова (місто)</option>
                            <option value="Лохвиця">Лохвиця</option>
                            <option value="Лубни">Лубни</option>
                            <option value="Луганськ">Луганськ</option>
                            <option value="Лутугине">Лутугине</option>
                            <option value="Луцьк">Луцьк</option>
                            <option value="Львів">Львів</option>
                            <option value="Любомль">Любомль</option>
                            <option value="Люботин">Люботин</option>
                            <option value="Макіївка">Макіївка</option>
                            <option value="Мала Виска">Мала Виска</option>
                            <option value="Малин">Малин</option>
                            <option value="Мар'їнка (місто)">Мар'їнка (місто)</option>
                            <option value="Марганець (місто)">Марганець (місто)</option>
                            <option value="Маріуполь">Маріуполь</option>
                            <option value="Мелітополь">Мелітополь</option>
                            <option value="Мена (місто)">Мена (місто)</option>
                            <option value="Мерефа">Мерефа</option>
                            <option value="Миколаїв (місто, Львівська область)">Миколаїв (місто, Львівська область)</option>
                            <option value="Миколаїв">Миколаїв</option>
                            <option value="Миколаївка (місто)">Миколаївка (місто)</option>
                            <option value="Миргород">Миргород</option>
                            <option value="Миронівка (місто)">Миронівка (місто)</option>
                            <option value="Міусинськ">Міусинськ</option>
                            <option value="Могилів-Подільський">Могилів-Подільський</option>
                            <option value="Молодогвардійськ">Молодогвардійськ</option>
                            <option value="Молочанськ">Молочанськ</option>
                            <option value="Монастириська">Монастириська</option>
                            <option value="Монастирище">Монастирище</option>
                            <option value="Моршин">Моршин</option>
                            <option value="Моспине">Моспине</option>
                            <option value="Мостиська">Мостиська</option>
                            <option value="Мукачеве">Мукачеве</option>
                            <option value="Надвірна">Надвірна</option>
                            <option value="Немирів">Немирів</option>
                            <option value="Нетішин">Нетішин</option>
                            <option value="Ніжин">Ніжин</option>
                            <option value="Нікополь">Нікополь</option>
                            <option value="Нова Каховка">Нова Каховка</option>
                            <option value="Нова Одеса">Нова Одеса</option>
                            <option value="Новгород-Сіверський">Новгород-Сіверський</option>
                            <option value="Новий Буг">Новий Буг</option>
                            <option value="Новий Калинів">Новий Калинів</option>
                            <option value="Новий Розділ">Новий Розділ</option>
                            <option value="Новоазовськ">Новоазовськ</option>
                            <option value="Нововолинськ">Нововолинськ</option>
                            <option value="Новоград-Волинський">Новоград-Волинський</option>
                            <option value="Новогродівка">Новогродівка</option>
                            <option value="Новодністровськ">Новодністровськ</option>
                            <option value="Новодружеськ">Новодружеськ</option>
                            <option value="Новомиргород">Новомиргород</option>
                            <option value="Новомосковськ">Новомосковськ</option>
                            <option value="Новоселиця (місто)">Новоселиця (місто)</option>
                            <option value="Новоукраїнка (місто)">Новоукраїнка (місто)</option>
                            <option value="Новояворівськ">Новояворівськ</option>
                            <option value="Носівка">Носівка</option>
                            <option value="Обухів">Обухів</option>
                            <option value="Овруч">Овруч</option>
                            <option value="Одеса">Одеса</option>
                            <option value="Олевськ">Олевськ</option>
                            <option value="Олександрівськ">Олександрівськ</option>
                            <option value="Олександрія">Олександрія</option>
                            <option value="Орджонікідзе (місто)">Орджонікідзе (місто)</option>
                            <option value="Оріхів">Оріхів</option>
                            <option value="Остер (місто)">Остер (місто)</option>
                            <option value="Острог">Острог</option>
                            <option value="Охтирка">Охтирка</option>
                            <option value="Очаків">Очаків</option>
                            <option value="П'ятихатки">П'ятихатки</option>
                            <option value="Павлоград">Павлоград</option>
                            <option value="Первомайськ (Луганська область)">Первомайськ (Луганська область)</option>
                            <option value="Первомайськ (Миколаївська область)">Первомайськ (Миколаївська область)</option>
                            <option value="Первомайський (місто)">Первомайський (місто)</option>
                            <option value="Перевальськ">Перевальськ</option>
                            <option value="Перемишляни">Перемишляни</option>
                            <option value="Перечин">Перечин</option>
                            <option value="Перещепине">Перещепине</option>
                            <option value="Переяслав-Хмельницький">Переяслав-Хмельницький</option>
                            <option value="Першотравенськ">Першотравенськ</option>
                            <option value="Петровське">Петровське</option>
                            <option value="Пирятин">Пирятин</option>
                            <option value="Південне (місто)">Південне (місто)</option>
                            <option value="Підгайці">Підгайці</option>
                            <option value="Підгородне">Підгородне</option>
                            <option value="Погребище">Погребище</option>
                            <option value="Пологи (місто)">Пологи (місто)</option>
                            <option value="Полонне">Полонне</option>
                            <option value="Полтава">Полтава</option>
                            <option value="Помічна">Помічна</option>
                            <option value="Попасна">Попасна</option>
                            <option value="Почаїв">Почаїв</option>
                            <option value="Привілля">Привілля</option>
                            <option value="Прилуки">Прилуки</option>
                            <option value="Приморськ">Приморськ</option>
                            <option value="Прип'ять (місто)">Прип'ять (місто)</option>
                            <option value="Пустомити">Пустомити</option>
                            <option value="Путивль">Путивль</option>
                            <option value="Рава-Руська">Рава-Руська</option>
                            <option value="Радехів">Радехів</option>
                            <option value="Радивилів">Радивилів</option>
                            <option value="Радомишль">Радомишль</option>
                            <option value="Рахів">Рахів</option>
                            <option value="Рені">Рені</option>
                            <option value="Ржищів">Ржищів</option>
                            <option value="Рівне">Рівне</option>
                            <option value="Ровеньки">Ровеньки</option>
                            <option value="Рогатин">Рогатин</option>
                            <option value="Родинське">Родинське</option>
                            <option value="Рожище">Рожище</option>
                            <option value="Роздільна">Роздільна</option>
                            <option value="Ромни">Ромни</option>
                            <option value="Рубіжне">Рубіжне</option>
                            <option value="Рудки">Рудки</option>
                            <option value="Саки">Саки</option>
                            <option value="Самбір">Самбір</option>
                            <option value="Сарни">Сарни</option>
                            <option value="Свалява">Свалява</option>
                            <option value="Сватове">Сватове</option>
                            <option value="Свердловськ">Свердловськ</option>
                            <option value="Світловодськ">Світловодськ</option>
                            <option value="Світлодарськ">Світлодарськ</option>
                            <option value="Святогірськ">Святогірськ</option>
                            <option value="Севастополь">Севастополь</option>
                            <option value="Селидове">Селидове</option>
                            <option value="Семенівка (місто)">Семенівка (місто)</option>
                            <option value="Середина-Буда">Середина-Буда</option>
                            <option value="Сєвєродонецьк">Сєвєродонецьк</option>
                            <option value="Синельникове">Синельникове</option>
                            <option value="Сіверськ">Сіверськ</option>
                            <option value="Сімферополь">Сімферополь</option>
                            <option value="Скадовськ">Скадовськ</option>
                            <option value="Скалат">Скалат</option>
                            <option value="Сквира">Сквира</option>
                            <option value="Сколе">Сколе</option>
                            <option value="Славута">Славута</option>
                            <option value="Славутич">Славутич</option>
                            <option value="Слов'янськ">Слов'янськ</option>
                            <option value="Сміла">Сміла</option>
                            <option value="Снігурівка (місто)">Снігурівка (місто)</option>
                            <option value="Сніжне">Сніжне</option>
                            <option value="Снятин">Снятин</option>
                            <option value="Сокаль">Сокаль</option>
                            <option value="Сокиряни">Сокиряни</option>
                            <option value="Соледар">Соледар</option>
                            <option value="Соснівка (місто)">Соснівка (місто)</option>
                            <option value="Старий Крим (місто)">Старий Крим (місто)</option>
                            <option value="Старий Самбір">Старий Самбір</option>
                            <option value="Старобільськ">Старобільськ</option>
                            <option value="Старокостянтинів">Старокостянтинів</option>
                            <option value="Стаханов">Стаханов</option>
                            <option value="Стебник">Стебник</option>
                            <option value="Сторожинець">Сторожинець</option>
                            <option value="Стрий">Стрий</option>
                            <option value="Судак (місто)">Судак (місто)</option>
                            <option value="Судова Вишня">Судова Вишня</option>
                            <option value="Суми">Суми</option>
                            <option value="Суходільськ">Суходільськ</option>
                            <option value="Таврійськ">Таврійськ</option>
                            <option value="Тальне">Тальне</option>
                            <option value="Тараща">Тараща</option>
                            <option value="Татарбунари">Татарбунари</option>
                            <option value="Теплодар">Теплодар</option>
                            <option value="Теребовля">Теребовля</option>
                            <option value="Тернівка (місто)">Тернівка (місто)</option>
                            <option value="Тернопіль">Тернопіль</option>
                            <option value="Тетіїв">Тетіїв</option>
                            <option value="Тисмениця (місто)">Тисмениця (місто)</option>
                            <option value="Тлумач">Тлумач</option>
                            <option value="Токмак">Токмак</option>
                            <option value="Торез">Торез</option>
                            <option value="Тростянець (місто)">Тростянець (місто)</option>
                            <option value="Трускавець">Трускавець</option>
                            <option value="Тульчин">Тульчин</option>
                            <option value="Турка">Турка</option>
                            <option value="Тячів">Тячів</option>
                            <option value="Угнів">Угнів</option>
                            <option value="Ужгород">Ужгород</option>
                            <option value="Узин">Узин</option>
                            <option value="Українка (місто)">Українка (місто)</option>
                            <option value="Українськ">Українськ</option>
                            <option value="Ульяновка (місто)">Ульяновка (місто)</option>
                            <option value="Умань">Умань</option>
                            <option value="Устилуг">Устилуг</option>
                            <option value="Фастів">Фастів</option>
                            <option value="Феодосія">Феодосія</option>
                            <option value="Харків">Харків</option>
                            <option value="Харцизьк">Харцизьк</option>
                            <option value="Херсон">Херсон</option>
                            <option value="Хирів">Хирів</option>
                            <option value="Хмельницький">Хмельницький</option>
                            <option value="Хмільник">Хмільник</option>
                            <option value="Ходорів">Ходорів</option>
                            <option value="Хорол (місто)">Хорол (місто)</option>
                            <option value="Хоростків">Хоростків</option>
                            <option value="Хотин">Хотин</option>
                            <option value="Христинівка">Христинівка</option>
                            <option value="Хуст">Хуст</option>
                            <option value="Цюрупинськ">Цюрупинськ</option>
                            <option value="Часів Яр">Часів Яр</option>
                            <option value="Червоноград">Червоноград</option>
                            <option value="Червонозаводське">Червонозаводське</option>
                            <option value="Червонопартизанськ">Червонопартизанськ</option>
                            <option value="Черкаси">Черкаси</option>
                            <option value="Чернівці">Чернівці</option>
                            <option value="Чернігів">Чернігів</option>
                            <option value="Чигирин">Чигирин</option>
                            <option value="Чоп">Чоп</option>
                            <option value="Чорнобиль">Чорнобиль</option>
                            <option value="Чортків">Чортків</option>
                            <option value="Чугуїв">Чугуїв</option>
                            <option value="Чуднів">Чуднів</option>
                            <option value="Шаргород">Шаргород</option>
                            <option value="Шахтарськ">Шахтарськ</option>
                            <option value="Шепетівка">Шепетівка</option>
                            <option value="Шостка">Шостка</option>
                            <option value="Шпола">Шпола</option>
                            <option value="Шумськ">Шумськ</option>
                            <option value="Щастя (місто)|Щаст">Щастя (місто)|Щаст</option>
                            <option value="Щолкіне">Щолкіне</option>
                            <option value="Щорс (місто)">Щорс (місто)</option>
                            <option value="Южне">Южне</option>
                            <option value="Южноукраїнськ">Южноукраїнськ</option>
                            <option value="Юнокомунарівськ">Юнокомунарівськ</option>
                            <option value="Яворів">Яворів</option>
                            <option value="Яготин">Яготин</option>
                            <option value="Ялта">Ялта</option>
                            <option value="Ямпіль (місто)">Ямпіль (місто)</option>
                            <option value="Яремче">Яремче</option>
                            <option value="Ясинувата">Ясинувата</option>
                        </select>
                    </p>
                    <p><label for="travel">Чи часто ви подорожуєте?</label>
                        <input type="radio" name="travel" value="0" checked style="display:inline;">ніколи
                        <input type="radio" name="travel" value="1" style="display:inline;" >раз на рік
                        <input type="radio" name="travel" value="2" style="display:inline;" >декілька раз на рік
                        <input type="radio" name="travel" value="3" style="display:inline;" >кожного місяця
                        <input type="radio" name="travel" value="4" style="display:inline;" >кожного тижня
                    </p>
                    <p><label for="migrate">Чи обдумували ви переїзд?</label>
                        <input type="radio" name="migrate" value="no" checked style="display:inline;">ні
                        <input type="radio" name="migrate" value="yes" style="display:inline;" >так
                    </p>
                    <p><label for="relax">Улюблені види відпочинку:</label>
                        <br><input type="checkbox" name="relax" value="TV" style="display:inline;" >перед телевізором 
                        <br><input type="checkbox" name="relax" value="PC" style="display:inline;" >перед комп’ютером
                        <br><input type="checkbox" name="relax" value="book" style="display:inline;" >перед книжкою
                        <br><input type="checkbox" name="relax" value="nature" style="display:inline;" >на природі
                        <br><input type="checkbox" name="relax" value="sea" style="display:inline;" >на морі
                        <br><input type="checkbox" name="relax" value="mountain" style="display:inline;" >в горах
                        <br><input type="checkbox" name="relax" value="history" style="display:inline;" >в історичних місцях
                        <br><input type="checkbox" name="relax" value="culture" style="display:inline;" >в культурних місцях


                    </p>
                    <p><input type="button" onclick="checkform()" value="Відправити" /></p>
                </form>
            
            </div>
            <div id="footer">
                <p>Копірайт © 2013-2014 Вербовий Андрій</p>
            </div>
        </div>
    </body>
</html>
